Add runner for vrap
NNPDF/runcards pull request #139
Opened 2022-06-14 12:19 UTC by scarlehoff

This thing _mostly_ work. But there are two (related) issues that I guess happen for the first time with vrap:

#### The `results` part of the runner.
If you try to run this it will fail at the end (after generating everything) when it tries to compare with the monte carlo results. There is no "MC result" to compare with in `vrap` (specially for the scale variations).

I could implement a reader for the central scale I guess or modify `vrap` to print the result in a more reasonable format, but is there a way to skip that...

#### One run-per-grid or one-grid-per-table...

There is a problem with some of the FTDY sets, the dataset for E905 is actually a set of 10 bins with different acceptances so we have a dataset that would need to generate 10 different pineappls. Here we have three choices:

1. Generate the 10 grids and apply the acceptance factors and them sum them together so that we have one single grid where the information of the singular runs have been lost.
2. Generate 20 E905_binX folders each with the kinematics of the given bin.
3. Accommodate for the fact that we can actually have grids that are a composition of other grids.

I guess 2. is similar to what we do for jets. But I wonder how terrible would be to do 1. directly here. In principle the acceptance factors are inherent to the dataset so the fact that the grid and the MC calculation don't match (this is where both issues are related) is secondary...

Also, please have a look at least to check that the structure is correct.

2022-06-14 12:20 UTC, scarlehoff commented
@enocera what do you think of option 1. above?: Basically burning the ACC factors in the grid.

2022-06-14 13:25 UTC, felixhekhorn commented on nnpdf31_proc/DYE605/inputDYE605nlo.dat
> +######################################################
Why has this file `nlo` in the name? wasn't the purpose of the exercise to produce NNLO grids?

2022-06-14 13:26 UTC, felixhekhorn commented on runcardsrunner/external/vrap.py
> +vrap blablabla
Please improve :upside_down_face:

2022-06-14 13:28 UTC, felixhekhorn commented on runcardsrunner/external/vrap.py
> +            sp.run(
I think we can do this also using the python interface ...

2022-06-14 13:33 UTC, felixhekhorn commented on runcardsrunner/external/vrap.py
> +        import numpy as np
is there a reason to delay this import? I think we have those two anyway in game ...

2022-06-14 13:36 UTC, scarlehoff commented on runcardsrunner/external/vrap.py
> +vrap blablabla
I worked hard on this documentation!

2022-06-14 13:37 UTC, scarlehoff commented on runcardsrunner/external/vrap.py
> +        import numpy as np
Because of what I say in the OP, that `results` method is just a placeholder.

2022-06-14 13:43 UTC, AleCandido commented
> I could implement a reader for the central scale I guess or modify `vrap` to print the result in a more reasonable format, but is there a way to skip that...

> * A comparison with the MC result (the central, not scale-varied result) is essential, we really need this check; basically the same check that we did. But skipping this for the time being is OK!

I just agree with @cschwan: if you want to skip, return something like a `None` from that method. In the consumer method, if a `None` is received, just print/log explicitly you're skipping this step and return (if you wish I can implement myself, but it should pretty simple anyhow).

2022-06-14 13:46 UTC, AleCandido commented on runcardsrunner/install.py
> +    version = "https://github.com/NNPDF/hawaiian_vrap/archive/refs/tags/1.0.tar.gz"
At the moment `collect_versions()` is only used for reporting purpose.

My personal suggestion would be to include it in the dedicated external module, and then reuse it from there.

Or maybe we can even collect all the versions of the program we are using into a single dedicated module (at least they are all together, and easy to query).

2022-06-14 13:52 UTC, AleCandido commented on runcardsrunner/external/vrap.py
> +            tmppine.unlink()
yeah, actually I would always use [context managers](https://docs.python.org/3/library/tempfile.html?highlight=tempfile#examples):
```py
with tempfile.TemporaryDirectory() as tmpdirname:
```

They are actually not deleting the folder (at least usually), but just because it is only a folder in `/tmp`, so it is fine to leave there (it is a `tmpfs` after all, either you reboot or you should schedule some cleanup periodically).

2022-06-14 13:57 UTC, AleCandido commented
@scarlehoff please add metadata files, like:
https://github.com/NNPDF/runcards/blob/97c1b9f5a658573c99d0ed8496bd6dfb406dd5f7/nnpdf31_proc/ATLAS_1JET_8TEV_R06/metadata.txt#L1-L13

2022-06-14 14:05 UTC, scarlehoff commented
> I suggest you detect Vrap by asking whether the directory contains one or more .dat file, this should be more robust than checking the dataset names (we might consider running Vrap for things other than fixed-target Drell-Yan)

`.dat` files are used for many different things. I can change the extension to `.vrap` 

> Wouldn't it be simpler to have one directory with one kinematics file and one runcard that would produce one grid? 

I honestly prefer the solution of burning in the acceptances...

> A comparison with the MC result (the central, not scale-varied result) is essential, we really need this check; basically the same check that we did. But skipping this for the time being is OK!

With the central is ok. I thought I also needed the scale variation (which I cannot get out of vrap in an easy manner rn)

2022-06-14 14:10 UTC, felixhekhorn commented
> `.dat` files are used for many different things. I can change the extension to `.vrap`

that is true and even applies in some sense to yadism which uses the very broad name "observable.yaml" - how about `.vrap.dat` and `.yadism.yaml` ?

2022-06-14 14:13 UTC, felixhekhorn commented
> 3\. Accommodate for the fact that we can actually have grids that are a composition of other grids.

if I remember correctly "composition" means "summing", isn't it?

2022-06-14 14:16 UTC, AleCandido reviewed
Mostly fine, just a few comments here and there.

I still have to run, I'll do later on :)

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/paths.py
>  lhapdf_dir = prefix / "lhapdf"
Since this is already more or less a data file, we can even add here the dictionary with versions :)

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/install.py
> +    condition = lambda: paths.vrap_exe.exists() and os.access(paths.vrap_exe, os.X_OK)
I know I was inconsistent myself, but `pylint` would complain about assigning a `lambda` to a name (since for it `lambda`s are only for anonymous purposes).

To be fair, I like it more like this, since a one-liner it is fine as a `lambda`, but the concept of "one-liner" is of course involved and not clearly defined.
However, if we decide we like this style, I will add to `.pylintrc` (to be moved inside `pyproject.toml`, by the way...) the exception.

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/install.py
> +    subprocess.run(["wget", version], cwd=tmp)
Actually, in the spirit of avoiding CLI as much as possible (it is not very Pythonic, and you might be more annoying to maintain), you could use `requests` package (it is already a dependency, and it's one of the [most popular Python packages](https://pypistats.org/top) in the first place ;D).

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/install.py
> +    subprocess.run(["wget", version], cwd=tmp)
See here:
https://github.com/NNPDF/runcards/blob/8a17a5a24829bec90db16cafbd423d769c507686/runcardsrunner/install.py#L246-L250

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/external/vrap.py
> +vrap blablabla
At some point we can even attempt to run here `pydocstyle` as in https://github.com/N3PDF/pineko/issues/23

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/external/vrap.py
> +                [paths.vrap_exe, self._input_card, kin_card], cwd=self.dest, check=True
Let's make a VRAP Python interface!

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/external/vrap.py
> +                [paths.vrap_exe, self._input_card, kin_card], cwd=self.dest, check=True
I'm joking...

2022-06-14 14:16 UTC, AleCandido commented on runcardsrunner/external/vrap.py
> +        return {}
Provide VRAP version, for reproducibility.

2022-06-14 14:16 UTC, scarlehoff commented
> > `.dat` files are used for many different things. I can change the extension to `.vrap`
> 
> that is true and even applies in some sense to yadism which uses the very broad name "observable.yaml" - how about `.vrap.dat` and `.yadism.yaml` ?

In this case I can just do `.vrap`. I'm using `.dat` because that's what was used before but it doesn't really matter.

> if I remember correctly "composition" means "summing", isn't it?

Yes, 

$$ E906 = \sum_{i} w^{j}_{i} grid_{ij} $$

2022-06-14 14:25 UTC, scarlehoff commented
> I still have to run, I'll do later on

Wait for it. I will fix the outstanding issues (mainly the results thing).

When finished it should work for all except for `E906`.

2022-06-14 14:33 UTC, scarlehoff commented
@AleCandido @felixhekhorn one question, what if instead of having an exact copy of the `vrap` input card I have a `vrap.yaml` file with the options and the runcard is generated automagically? Would that be ok? Or do we want an "original runcard" that can be run without the runner?

2022-06-14 14:49 UTC, enocera commented
> @enocera what do you think of option 1. above?: Basically burning the ACC factors in the grid.

I think that this is consistent, in perspective, with what we discussed more generally about NNLO QCD K-factors at the code meeting in Milan. If I'm not wrong, the proposal was to incorporate K-factors into grids, so that these do not need to be specified in the fit runcards anymore. While in the future it is more likely that we will get rid of NNLO QCD K-factors by computing NNLO grids exactly, rather than by incorporating K-factors into grids, all K-factors are created equal in this respect. So it'd be silly to get rid of NNLO QCD K-factors, but not of ACC K-factors.

2022-06-14 14:50 UTC, scarlehoff commented
Then I will simply add the ACC factors to E906.

2022-06-14 14:50 UTC, enocera commented
This is a very complicated way of saying that, of all options, I'm in favour of option 1.

2022-06-14 14:54 UTC, scarlehoff commented on runcardsrunner/install.py
> +    version = "https://github.com/NNPDF/hawaiian_vrap/archive/refs/tags/1.0.tar.gz"
But at the time of the installer the runner doesn't have access to `collect version` right?

2022-06-14 14:54 UTC, scarlehoff commented on runcardsrunner/install.py
> +    condition = lambda: paths.vrap_exe.exists() and os.access(paths.vrap_exe, os.X_OK)
I was just cargo-culting the madgraph installer... happy to change it in any way you guys prefer.

2022-06-14 15:24 UTC, AleCandido commented
> all K-factors are created equal

[Yes sir](https://en.wikipedia.org/wiki/All_men_are_created_equal) :us: :eagle:

2022-06-14 15:39 UTC, felixhekhorn commented on runcardsrunner/external/vrap.py
> +    Uses a modified version of pineappl https://github.com/NNPDF/hawaiian_vrap
```suggestion
    Uses a modified version of vrap https://github.com/NNPDF/hawaiian_vrap
```

2022-06-14 15:42 UTC, felixhekhorn commented on runcardsrunner/external/vrap.py
> +        return {"version": VERSION}
should we prefix the key? á là `"vrap_version"`

2022-06-14 16:46 UTC, cschwan commented on runcardsrunner/external/vrap.py
> +        return {"version": VERSION}
Yes, please, `version` is to too general.

2022-06-14 17:40 UTC, scarlehoff commented on runcardsrunner/external/vrap.py
> +        return {"version": str(VERSION)}
```suggestion
        return {"vrap_version": str(VERSION)}
```

2022-06-15 08:43 UTC, felixhekhorn commented on nnpdf31_proc/DYE605/metadata.txt
> +description=Drell-Yan experiment E605
The information that this is fixed-target is relevant - please add (here and elsewhere)

2022-06-15 08:57 UTC, cschwan commented on nnpdf31_proc/DYE605/metadata.txt
> +hepdata=10.17182/hepdata.22831
Another point: if we burn in the acceptance factors then the units probably change to 'counts' or something similar.

2022-06-15 08:57 UTC, felixhekhorn commented on nnpdf31_proc/DYE605/metadata.txt
> +y_unit=pb GeV2
- for the content see comment above
- for the style: let's be consistent and use `^` in the units as power symbol (@cschwan ?)

2022-06-15 09:07 UTC, felixhekhorn commented on nnpdf31_proc/DYE906R_D/metadata.txt
> +y_label_tex=$d\sigma_{pd}$
this doesn't seem correct ... remove initial `d`?

2022-06-15 09:10 UTC, AleCandido commented on nnpdf31_proc/DYE906R_D/metadata.txt
> +y_label_tex=$d\sigma_{pd}$
Only if it is inclusive. Otherwise keep it and spell out the variables in the differential.

2022-06-15 09:12 UTC, felixhekhorn commented on nnpdf31_proc/DYE906R_D/vrap.yaml
> +jacobian866: "Yes"
just a minor comment you can safely ignore: if `jacobian866` is also used for E906 than maybe it's not the best name :upside_down_face:

2022-06-15 09:19 UTC, felixhekhorn commented on runcardsrunner/install.py
> +    with tempfile.TemporaryDirectory() as tmp:
Shouldn't we follow the others (pineappl, mg5) and install into `.prefix`? i.e. make a variable in `paths` and use that one?

2022-06-15 09:21 UTC, AleCandido commented on runcardsrunner/install.py
> +    with tempfile.TemporaryDirectory() as tmp:
I thought it was actually installing in `prefix`, why don't you believe so @felixhekhorn?

https://github.com/NNPDF/runcards/blob/9fb8018545a25d7528f2c966db268f9f1173c954/runcardsrunner/install.py#L96-L98

2022-06-15 09:25 UTC, felixhekhorn commented on runcardsrunner/install.py
> +    with tempfile.TemporaryDirectory() as tmp:
okay, it is installing there  - but not extracting to it, maybe that's fine ...

2022-06-15 09:30 UTC, scarlehoff commented on nnpdf31_proc/DYE906R_D/vrap.yaml
> +jacobian866: "Yes"
Yes, this was a bad choice of name and tbh it is not necessary for E906 (because it is a ratio and the jacobians cancel out). Maybe jacobianApfel would've been better.

2022-06-15 09:37 UTC, scarlehoff commented on nnpdf31_proc/DYE605/metadata.txt
> +hepdata=10.17182/hepdata.22831
605 has no acceptance factors. This is 906.

With respect to the inconsistencies, I will copy what's in `filters/FTDY.cc`, not sure what to do here...

```
 *     The format of data is for the paper:
 *
 *     y   sqrt(tau)  s*d^2sigma/dsqt(tau)/dy [pb GeV2 / nucleon]  stat(abs.)
 *
 *     but for the tables from HEPDATA, in the file data/dy-E605/dy-e605.data
 *     one has instead
 *
 *     y   sqrt(tau)  s*d^2sigma/dsqt(tau)/dy [cm2 GeV2 / nucleon]  stat(abs.)
```

Where should I add the information about this inconsistencies?

The units I took from there. Instead the label_tex I automatically filled from the plotting file and I didn't realise they were different (because I guess they refer to different things?) I guess here the correct one would instead be instead the one in `FTDY.cc`. Fixed.

```
s*d^2sigma/dsqt(tau)/dy
```

2022-06-15 09:40 UTC, AleCandido commented on nnpdf31_proc/DYE605/metadata.txt
> +hepdata=10.17182/hepdata.22831
The inconsistency is now less inconsistent:
```
s*d^2sigma/dsqt(tau)/dy
```
There is a factor of `s`, that is actually `GeV2`, so it looks like the units are fine, but for the factor `sqrt(tau)`.

2022-06-15 09:43 UTC, scarlehoff commented on nnpdf31_proc/DYE605/metadata.txt
> +y_unit=pb GeV2
> y_label should correspond to y_label_tex

In what sense? Should I describe `y_label_tex`. Or write `y_label_tex` in a more or less clear-text format?

Something like:

```
y_label_tex = $s*\frac{d^2\sigma}{d\sqt(\tau)dy}$
y_label=s*d^2sigma/dsqt(tau)/dy
```

??

2022-06-15 09:43 UTC, AleCandido commented on nnpdf31_proc/DYE906R_D/vrap.yaml
> +jacobian866: "Yes"
I would avoid references to APFEL, since we're going to no longer use it. Why is `jacobian` only ambiguous?

2022-06-15 09:46 UTC, scarlehoff commented on nnpdf31_proc/DYE906R_D/vrap.yaml
> +jacobian866: "Yes"
Because it doesn't explain what it does. It really only has an effect for E866.

I'm tracking all `vrap` issues that are arising here in the vrap repo and once I fixed them there I'll update the runner with the appropriate changes.

2022-06-15 09:46 UTC, scarlehoff commented on nnpdf31_proc/DYE605/metadata.txt
> +hepdata=10.17182/hepdata.22831
Ups, yes, thanks.

2022-06-15 09:51 UTC, scarlehoff commented
Please have a look at the `metadata.txt` for E605. I think I understood now what to put where. If I did, I will update all the others accordingly.

2022-06-15 09:52 UTC, AleCandido commented on nnpdf31_proc/DYE906R_D/vrap.yaml
> +jacobian866: "Yes"
But then, what is actually doing? If it has an effect only on E866, but it's just the only instance of a may-be-generic feature, I'd say it's safe to assign a more generic name (not so relevant in practice you only have one instance).
Otherwise, why does E866 deserve a tailored thing?

2022-06-15 10:00 UTC, scarlehoff commented on nnpdf31_proc/DYE906R_D/vrap.yaml
> +jacobian866: "Yes"
> why does E866 deserve a tailored thing?

Only E605 and E866 have a dataset that is not a ratio (where the jacobians do matter) and are inconsistent among themselves (one is d sigma / d tau  and the other d sigma / dM), the jacobian is for tau -> M. So it was a jacobian for the inconsistency of E866.

Then since the fktables produced with apfel for E906 where also d sigma / d M for that dataset (even though the jacobian cancels out in the dataset) I decided to put the label also there, but it is not necessary since they only get accessed as a ratio.

So it only has a practical effect in E866 and the option is needed to produce results differential in tau or M, so it should've called jacobianTau2M or something (and that's what I will change it to).

2022-06-15 10:14 UTC, felixhekhorn commented on nnpdf31_proc/DYE605/metadata.txt
> +y_label=s*d^2sigma/dsqrt(tau)/dy
I think `y_label` will be used in CLI outputs (@cschwan ?) and then this might be too long  ... I've no good counter proposal though ... `sd2sig/dst/dy`?

2022-06-15 10:34 UTC, scarlehoff commented
@enocera I haven't been able to find the exact table the data for E866 is taken from? In the hepdata entry that is linked in the filters I can only find the data for E866R but not for E866 https://www.hepdata.net/record/ins554316 ?

2022-06-15 10:45 UTC, AleCandido commented on nnpdf31_proc/DYE866/metadata.txt
> +hepdata=???????
Ok, these are actually interesting.

Maybe some external help, e.g. @enocera?

2022-06-15 10:48 UTC, AleCandido commented on nnpdf31_proc/DYE866/metadata.txt
> +hepdata=???????
Ok, sorry, I haven't seen that you already called for help @scarlehoff, my bad.

2022-06-15 11:06 UTC, cschwan commented on nnpdf31_proc/DYE605/metadata.txt
> +y_label=s*d^2sigma/dsqrt(tau)/dy
@felixhekhorn right. For the time being `y_label` is used in `pineappl convolute`, for instance, and `y_label_tex` in `pineappl plot`.

2022-06-15 11:12 UTC, enocera commented on nnpdf31_proc/DYE866/metadata.txt
> +hepdata=???????
The relevant entry inspire entry is the following
https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=hep-ex%2F0302019&ui-citation-summary=true
which means that 
`arxiv=hep-ex/0302019`
`hepdata=10.17182/hepdata.41970.v1`

2022-06-15 11:13 UTC, enocera commented on nnpdf31_proc/DYE866/metadata.txt
> +hepdata=???????
@scarlehoff Not surprised that you weren't able to find the hepdata entry in the filters files - these are dreadful. Hopefully the situation will improve very much and very soon with the new commondata format.

2022-06-15 11:16 UTC, enocera commented
> It is only a bit weird (or just unexpected) that `sqrt(tau)` is dimensionless, but now everything is consistent.

$\tau$ IS dimensionless, as it is defined as $\tau=M^2/s$, see Eq. (5) in https://arxiv.org/pdf/1002.4407.pdf.

2022-06-15 12:05 UTC, cschwan commented on nnpdf31_proc/DYE866/metadata.txt
> +hepdata=???????
Let's also add `inspirehep=613362` (see https://github.com/NNPDF/runcards/issues/136).

2022-06-21 10:52 UTC, scarlehoff commented
This runner works only with pineappl 0.53 since it uses https://github.com/N3PDF/pineappl/issues/148

2022-06-21 12:14 UTC, scarlehoff commented
Yes, I haven't updated so that it doesn't fail because 0.5.3 doesn't exit. When it is released I'll update this and then it can be merged (no point on merging it before 0.5.3 exists)

2022-06-21 12:27 UTC, AleCandido commented
[v0.5.3b2](https://pypi.org/project/pineappl/0.5.3b2/) exists, the only problem is that you need an explicit toggle to tell Poetry to accept a pre-released version.

2022-06-22 07:42 UTC, cschwan commented
I've just released [v0.5.3](https://github.com/N3PDF/pineappl/releases/tag/v0.5.3), that should make things a bit easier.

2022-06-22 14:03 UTC, scarlehoff commented
Thanks @cschwan  This can be merged then (subjected to review/approval).

2022-06-24 10:44 UTC, AleCandido commented on nnpdf31_proc/DYE605/vrap.yaml
> +#####################################################
This runcard has headers, while the other have not. It doesn't care the less, of course, but for future I would avoid, simply because it is harder to be consistent in including them ^^

2022-06-24 10:47 UTC, scarlehoff commented on nnpdf31_proc/DYE605/vrap.yaml
> +#####################################################
I can remove them.

2022-06-24 10:49 UTC, AleCandido commented on nnpdf31_proc/DYE605/vrap.yaml
> +#####################################################
No need, it was just a mention, but since you've that's perfect :)

2022-06-24 11:10 UTC, AleCandido requested changes
I read it all, but still need to test (I'm running `poetry update` at the moment because lockfile was outdated).

Apart from a couple of minor comments, I'd say it's ready. Just let me run once :)

2022-06-24 11:10 UTC, AleCandido commented on runcardsrunner/external/vrap.py
> +_PINEAPPL = "test.pineappl.lz4"
Is this a standard name used inside `vrap`?

Because I see you never passed to it, and you are reading a file with that name below (only usage), so that file is supposed to exist.

I don't know how much complicate would be, but instead of relying on the two programs using the same name, I would either pass `vrap` an argument, telling the destination file name, or read this name from it.

Of course, if it is exceedingly complicated, never mind.

2022-06-24 11:10 UTC, AleCandido commented on runcardsrunner/install.py
> +    url = "https://github.com/NNPDF/hawaiian_vrap/releases/latest/download/vrap.tar.gz"
Given bad experience in other cases, I'm not sure using `latest` is a great idea.
Maybe just replace with the current version, at least with this code the installation is reproducible, even if a new release of `vrap` will change something.

Of course the version will be logged in the run, but this way we'd make it harder (though still possible) to reproduce, for no special reason.

2022-06-24 11:10 UTC, AleCandido commented on runcardsrunner/install.py
> +    url = "https://github.com/NNPDF/hawaiian_vrap/releases/latest/download/vrap.tar.gz"
If you wish, you can store version in a module level constant. Maybe at some point we'll collect all of them in a single module.

2022-06-24 11:34 UTC, scarlehoff commented on runcardsrunner/external/vrap.py
> +_PINEAPPL = "test.pineappl.lz4"
> Is this a standard name used inside vrap?

Yes. I can change it. 

(I won't right now but I've opened the issue https://github.com/NNPDF/hawaiian_vrap/issues/19 so when I restart vrap development for NNLO I remember to do that)

2022-06-24 11:50 UTC, scarlehoff commented
I've fixed the version.
The thing about the name will be changed in vrap in the future but for now it is like that.

Could you fix the conflict in yad.py @AleCandido ?

2022-06-24 12:42 UTC, AleCandido commented
Rebased on current master, it was just an `import` issue. Solved.

I'll test and (assume it's working) we'll merge :)

2022-06-24 13:54 UTC, AleCandido approved these changes

2022-07-21 13:06 UTC, merged